import { Metadata } from "next";

import "./globals.css";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Ramos Uc</title>
      </head>
      <body>
        <main className="flex min-h-screen w-full flex-col">{children}</main>
        <footer className="mt-auto bg-gray-900 py-6 text-center text-white">
          <div className="container mx-auto">
            <p className="text-sm text-gray-400">
              © {new Date().getFullYear()} Ramos UC. Todos los derechos reservados. Open Source UC.
            </p>
          </div>
        </footer>
        <Header /> {/* ✅ Add the Header component here */}
        <main className="mt-16 flex w-full flex-col">{children}</main> {/* ✅ Add mt-16 to prevent overlap */}
      </body>
    </html>
  );
}
